repository:
  name: random1on1s-bot
  description: Python discord bot that  
  topics: discord, discord-bot 
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: 
            - qwinters
            - stevenmaio
            - bajoukx
            - weierstrash
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
