name: Release new bot version 
on:
  push:
    tags:
      - '*.*.*' 
jobs:
  build:
    name: Release notes + homework + changelog on website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create changelog based on git commit history
        id: generate_changelog
        uses: scottbrenner/generate-changelog-action@master
        with: 
          package-dir: ".github/configs/package.json" 
          exclude: chore
      - name: Add changelog to repo
        id: git_add_changelog
        shell: bash 
        run: |
            curr_tag=$(git describe --tags)
            git config --local user.name "github-action"
            git checkout main
            echo "${{ steps.generate_changelog.outputs.changelog }}" >> CHANGELOG.md
            git add CHANGELOG.md 
            git commit -m "chore: Changelog for release ${{ github.ref }}"
            git push
            git checkout $curr_tag
      - name: Create Release
        id: release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false
